module.exports = [
    {
        "address": "10 Ubi Crescent CORE E #07-88 Ubi Techpark",
        "charged_under_id": 1,
        "company_email": "osimonis@leannon.com",
        "company_name": "Tromp-Swift",
        "description": "Function-Based Didactic Matrix",
        "gst": true,
        "gst_show": true,
        "name": "John White",
        "p1_name": "John White",
        "p1_phone_number": "67411927",
        "postal_code": "408564"
    },
    {
        "address": "33D Benoi Road",
        "charged_under_id": 1,
        "company_email": "jarret74@conn.biz",
        "company_name": "Nolan and Sons",
        "description": "Devolved Zerodefect Array",
        "gst": true,
        "gst_show": true,
        "name": "Michael Wilson",
        "p1_name": "Michael Wilson",
        "p1_phone_number": "68638461",
        "postal_code": "627788"
    },
    {
        "address": "10 Anson Road #05-16 International Plaza",
        "charged_under_id": 1,
        "company_email": "renner.jammie@schowalter.com",
        "company_name": "Lindgren Ltd",
        "description": "Adaptive Cohesive Analyzer",
        "gst": true,
        "gst_show": true,
        "name": "Fred Pollard",
        "p1_name": "Fred Pollard",
        "p1_phone_number": "62241892",
        "postal_code": "079903"
    },
    {
        "address": "630 Hougang Ave 8 #01-K1",
        "charged_under_id": 1,
        "company_email": "bmoore@lindgren.biz",
        "company_name": "Hyatt LLC",
        "description": "Organic Exuding Architecture",
        "gst": true,
        "gst_show": true,
        "name": "Timothy Wolfe",
        "p1_name": "Timothy Wolfe",
        "p1_phone_number": "62831946",
        "postal_code": "530630"
    },
    {
        "address": "BLK 38 DEFU LANE 10#02-03",
        "charged_under_id": 1,
        "company_email": "ljacobi@bradtke.com",
        "company_name": "Walter-Krajcik",
        "description": "Multi-Lateral Motivating Moderator",
        "gst": true,
        "gst_show": true,
        "name": "Christopher Hamilton",
        "p1_name": "Christopher Hamilton",
        "p1_phone_number": "62845263",
        "postal_code": "539215"
    },
    {
        "address": "16 Raffles Quay #01-07 Hong Leong Building",
        "charged_under_id": 1,
        "company_email": "wthompson@schuster.info",
        "company_name": "Senger Ltd",
        "description": "Cross-Group Tertiary Customerloyalty",
        "gst": true,
        "gst_show": true,
        "name": "Troy Payne",
        "p1_name": "Troy Payne",
        "p1_phone_number": "62204724",
        "postal_code": "048581"
    },
    {
        "address": "390 Victoria St #05-01",
        "charged_under_id": 1,
        "company_email": "richie.schoen@little.com",
        "company_name": "Rempel, Mraz and Bailey",
        "description": "Integrated Web-Enabled Monitoring",
        "gst": true,
        "gst_show": true,
        "name": "Erica Santos",
        "p1_name": "Erica Santos",
        "p1_phone_number": "62975364",
        "postal_code": "188061"
    },
    {
        "address": "3007 UBI RD 1 04-452/454",
        "charged_under_id": 1,
        "company_email": "bweissnat@toy.com",
        "company_name": "Larkin, Mitchell and Ondricka",
        "description": "Profound Optimizing Policy",
        "gst": true,
        "gst_show": true,
        "name": "Katherine Mooney",
        "p1_name": "Katherine Mooney",
        "p1_phone_number": "67460814",
        "postal_code": "408701"
    },
    {
        "address": "14, Scotts Rd #04-31, Far East Plaza",
        "charged_under_id": 1,
        "company_email": "tspinka@buckridge.biz",
        "company_name": "Kihn-Rice",
        "description": "Enhanced Cohesive Function",
        "gst": true,
        "gst_show": true,
        "name": "Mitchell Franklin",
        "p1_name": "Mitchell Franklin",
        "p1_phone_number": "65-67381799",
        "postal_code": "228213"
    },
    {
        "address": "8 Temasek Boulevard Suntec Tower Three",
        "charged_under_id": 1,
        "company_email": "rbartoletti@kirlin.info",
        "company_name": "Pfannerstill-Ortiz",
        "description": "Sharable Discrete Model",
        "gst": true,
        "gst_show": true,
        "name": "Sara Meyer",
        "p1_name": "Sara Meyer",
        "p1_phone_number": "62388964",
        "postal_code": "038988"
    },
    {
        "address": "109 North Bridge Road #02-20/21/22 FUNAN THE IT MALL",
        "charged_under_id": 1,
        "company_email": "macejkovic.jailyn@shanahan.com",
        "company_name": "Barrows, Kirlin and Osinski",
        "description": "Visionary Dynamic Matrix",
        "gst": true,
        "gst_show": true,
        "name": "Allison Baker",
        "p1_name": "Allison Baker",
        "p1_phone_number": "63342212",
        "postal_code": "179097"
    },
    {
        "address": "371 Beach Road #22-06 KEYPOINT",
        "charged_under_id": 1,
        "company_email": "vwisoky@walter.com",
        "company_name": "Wolf, Barrows and Mante",
        "description": "Multi-Lateral Global Utilisation",
        "gst": true,
        "gst_show": true,
        "name": "Donna Hall",
        "p1_name": "Donna Hall",
        "p1_phone_number": "63363975",
        "postal_code": "199597"
    },
    {
        "address": "273 Thomson Rd Novena Gdns",
        "charged_under_id": 1,
        "company_email": "kohler.mariana@rodriguez.org",
        "company_name": "Leffler Group",
        "description": "Front-Line 3Rdgeneration Support",
        "gst": true,
        "gst_show": true,
        "name": "Mary Rios",
        "p1_name": "Mary Rios",
        "p1_phone_number": "62543333",
        "postal_code": "307644"
    },
    {
        "address": "toa payoh community library 6 toa payoh central level 3",
        "charged_under_id": 1,
        "company_email": "everardo.trantow@zulauf.info",
        "company_name": "Bogan Ltd",
        "description": "De-Engineered Optimizing Task-Force",
        "gst": true,
        "gst_show": true,
        "name": "Latasha Bray",
        "p1_name": "Latasha Bray",
        "p1_phone_number": "0 6354 5139",
        "postal_code": "319191"
    },
    {
        "address": "196 Pandan Loop #04-04 PANTECH INDUSTRIAL COMPLEX",
        "charged_under_id": 1,
        "company_email": "allene11@waters.com",
        "company_name": "Abernathy, McCullough and McGlynn",
        "description": "Exclusive Actuating Neural-Net",
        "gst": true,
        "gst_show": true,
        "name": "Kelly Holland",
        "p1_name": "Kelly Holland",
        "p1_phone_number": "63922546",
        "postal_code": "128384"
    },
    {
        "address": "No 3, Jurong West Street 1, , 21-00",
        "charged_under_id": 1,
        "company_email": "koch.heaven@hoppe.com",
        "company_name": "Hane-Hickle",
        "description": "Open-Architected Assymetric Parallelism",
        "gst": true,
        "gst_show": true,
        "name": "Faith Chandler",
        "p1_name": "Faith Chandler",
        "p1_phone_number": "65-955-41168",
        "postal_code": "609649"
    },
    {
        "address": "10 Anson Road ,27-18 International Plaza S()",
        "charged_under_id": 1,
        "company_email": "kirsten26@will.net",
        "company_name": "Bins-Stanton",
        "description": "Sharable 3Rdgeneration Ability",
        "gst": true,
        "gst_show": true,
        "name": "Alan Brooks",
        "p1_name": "Alan Brooks",
        "p1_phone_number": "65-68534321",
        "postal_code": "079903"
    },
    {
        "address": "115 Bedok North Road 12-305",
        "charged_under_id": 1,
        "company_email": "eda89@stokes.org",
        "company_name": "Reinger, Auer and Crona",
        "description": "Facetoface Tertiary Flexibility",
        "gst": true,
        "gst_show": true,
        "name": "Christina Hill",
        "p1_name": "Christina Hill",
        "p1_phone_number": "64253425",
        "postal_code": "460115"
    },
    {
        "address": "400 Orchard Road 08-01 Orchard Towers",
        "charged_under_id": 1,
        "company_email": "claudie83@graham.net",
        "company_name": "Strosin, Lebsack and Hoppe",
        "description": "Compatible Context-Sensitive Database",
        "gst": true,
        "gst_show": true,
        "name": "Nancy Lopez",
        "p1_name": "Nancy Lopez",
        "p1_phone_number": "67323156",
        "postal_code": "238875"
    },
    {
        "address": "Shopping Centre 190 Clemenceau Avenue #07-02",
        "charged_under_id": 1,
        "company_email": "yolanda36@fisher.com",
        "company_name": "Renner, Torphy and Hagenes",
        "description": "Synergistic Discrete Circuit",
        "gst": true,
        "gst_show": true,
        "name": "Leslie Howell",
        "p1_name": "Leslie Howell",
        "p1_phone_number": "63385887",
        "postal_code": "239924"
    },
    {
        "address": "457 Hougang Avenue 10 03-429",
        "charged_under_id": 1,
        "company_email": "gmraz@quitzon.info",
        "company_name": "Zulauf PLC",
        "description": "Compatible Non-Volatile Superstructure",
        "gst": true,
        "gst_show": true,
        "name": "Jessica Hughes",
        "p1_name": "Jessica Hughes",
        "p1_phone_number": "63850560",
        "postal_code": "530457"
    },
    {
        "address": "No. 503, , 12-159, Choa Chu Kang St. 51",
        "charged_under_id": 1,
        "company_email": "zgrimes@schneider.com",
        "company_name": "Fritsch-Schultz",
        "description": "Customer-Focused Nextgeneration Analyzer",
        "gst": true,
        "gst_show": true,
        "name": "Kevin Kim",
        "p1_name": "Kevin Kim",
        "p1_phone_number": "65-00-64016376",
        "postal_code": "680503"
    },
    {
        "address": "16 PANDAN LOOP, #01-121",
        "charged_under_id": 1,
        "company_email": "okon.marjory@moore.com",
        "company_name": "Ebert PLC",
        "description": "Multi-Tiered Neutral Project",
        "gst": true,
        "gst_show": true,
        "name": "Benjamin Wright",
        "p1_name": "Benjamin Wright",
        "p1_phone_number": "63410044",
        "postal_code": "128234"
    },
    {
        "address": "Blk 102C Punggol Field ,09-414",
        "charged_under_id": 1,
        "company_email": "swilliamson@howell.com",
        "company_name": "Cremin PLC",
        "description": "Multi-Tiered Intangible Capability",
        "gst": true,
        "gst_show": true,
        "name": "Angela Johnson",
        "p1_name": "Angela Johnson",
        "p1_phone_number": "65-94502751",
        "postal_code": "823102"
    },
    {
        "address": "353 Jurong East Street 31 02-111",
        "charged_under_id": 1,
        "company_email": "bailey.anya@kuhn.com",
        "company_name": "Lowe, Watsica and Goyette",
        "description": "Customizable Content-Based Analyzer",
        "gst": true,
        "gst_show": true,
        "name": "Caitlin Griffith",
        "p1_name": "Caitlin Griffith",
        "p1_phone_number": "68998146",
        "postal_code": "600353"
    },
    {
        "address": "43 Holland Drive, #01-67",
        "charged_under_id": 1,
        "company_email": "mckenzie.danika@spinka.com",
        "company_name": "Olson-McDermott",
        "description": "Profit-Focused Contextually-Based Ability",
        "gst": true,
        "gst_show": true,
        "name": "Chelsea King",
        "p1_name": "Chelsea King",
        "p1_phone_number": "65 6776 0082",
        "postal_code": "270043"
    },
    {
        "address": "1 Jalan Kilang 03-02 / 04-02 Dynasty Building",
        "charged_under_id": 1,
        "company_email": "laurianne.vandervort@barton.com",
        "company_name": "Heller Inc",
        "description": "Universal Bi-Directional Orchestration",
        "gst": true,
        "gst_show": true,
        "name": "Kristen Williams",
        "p1_name": "Kristen Williams",
        "p1_phone_number": "62744592",
        "postal_code": "159402"
    },
    {
        "address": "112 Middle Rd #05-00",
        "charged_under_id": 1,
        "company_email": "smckenzie@mueller.com",
        "company_name": "Schulist-Wiza",
        "description": "Implemented Multimedia Time-Frame",
        "gst": true,
        "gst_show": true,
        "name": "Robert Schmidt",
        "p1_name": "Robert Schmidt",
        "p1_phone_number": "63383424",
        "postal_code": "188970"
    },
    {
        "address": "6 Eunos Crescent #01-2641",
        "charged_under_id": 1,
        "company_email": "jared81@turcotte.com",
        "company_name": "Mann-Pacocha",
        "description": "Versatile Regional Ability",
        "gst": true,
        "gst_show": true,
        "name": "Jenna Gray",
        "p1_name": "Jenna Gray",
        "p1_phone_number": "67440077",
        "postal_code": "400006"
    },
    {
        "address": "1000 East Coast Parkway Marine Cove S()",
        "charged_under_id": 1,
        "company_email": "ritchie.jovanny@beahan.com",
        "company_name": "Schneider LLC",
        "description": "Compatible Multi-Tasking Algorithm",
        "gst": true,
        "gst_show": true,
        "name": "Donna Bailey",
        "p1_name": "Donna Bailey",
        "p1_phone_number": "(65) 62444415",
        "postal_code": "449876"
    },
    {
        "address": "52 Woodlands St 13 #01-10 S()",
        "charged_under_id": 1,
        "company_email": "graham.kassandra@heidenreich.biz",
        "company_name": "Hackett-Keeling",
        "description": "Fully-Configurable Exuding Migration",
        "gst": true,
        "gst_show": true,
        "name": "Abigail Rodriguez",
        "p1_name": "Abigail Rodriguez",
        "p1_phone_number": "(65) 63689717",
        "postal_code": "738603"
    },
    {
        "address": "35 FISHERY PORT ROAD RM 227",
        "charged_under_id": 1,
        "company_email": "zieme.ada@russel.com",
        "company_name": "Brakus PLC",
        "description": "Adaptive Systemic Strategy",
        "gst": true,
        "gst_show": true,
        "name": "Jennifer Martinez",
        "p1_name": "Jennifer Martinez",
        "p1_phone_number": "62651617",
        "postal_code": "619742"
    },
    {
        "address": "Chinatown Complex (U/C) 335 Smith Street #16-51",
        "charged_under_id": 1,
        "company_email": "muller.anahi@okuneva.com",
        "company_name": "Lesch Ltd",
        "description": "Streamlined Responsive Infrastructure",
        "gst": true,
        "gst_show": true,
        "name": "Ryan Thomas",
        "p1_name": "Ryan Thomas",
        "p1_phone_number": "62207750",
        "postal_code": "050335"
    },
    {
        "address": "Blk 928 Jurong West St92",
        "charged_under_id": 1,
        "company_email": "werner39@hickle.info",
        "company_name": "Graham-Lynch",
        "description": "Robust Web-Enabled Definition",
        "gst": true,
        "gst_show": true,
        "name": "Jacob Boyd",
        "p1_name": "Jacob Boyd",
        "p1_phone_number": "65-63372285-63372285",
        "postal_code": "640928"
    },
    {
        "address": "3 Science Park Drive 01-05 The Franklin",
        "charged_under_id": 1,
        "company_email": "ryder93@carroll.net",
        "company_name": "Goodwin, Daniel and Kihn",
        "description": "De-Engineered User-Facing Capacity",
        "gst": true,
        "gst_show": true,
        "name": "Rhonda Jackson",
        "p1_name": "Rhonda Jackson",
        "p1_phone_number": "67779643",
        "postal_code": "118223"
    },
    {
        "address": "865 Mountbatten Rd #07-01",
        "charged_under_id": 1,
        "company_email": "gregory.farrell@collier.com",
        "company_name": "Lesch-Prosacco",
        "description": "Re-Contextualized Cohesive Superstructure",
        "gst": true,
        "gst_show": true,
        "name": "Rachel Haynes",
        "p1_name": "Rachel Haynes",
        "p1_phone_number": "63454754",
        "postal_code": "437844"
    },
    {
        "address": "Great Eastern Building #02-01G, 200 Changi Road",
        "charged_under_id": 1,
        "company_email": "kristopher.dickinson@gaylord.com",
        "company_name": "Cartwright-Rosenbaum",
        "description": "Realigned Bandwidth-Monitored Orchestration",
        "gst": true,
        "gst_show": true,
        "name": "Sydney Ruiz",
        "p1_name": "Sydney Ruiz",
        "p1_phone_number": "65 6417 5493",
        "postal_code": "419734"
    },
    {
        "address": "West Bay Condominium 52 West Coast Crescent #01-04",
        "charged_under_id": 1,
        "company_email": "lfeil@cummerata.org",
        "company_name": "Denesik-Anderson",
        "description": "Re-Engineered Value-Added Adapter",
        "gst": true,
        "gst_show": true,
        "name": "Heather Miller",
        "p1_name": "Heather Miller",
        "p1_phone_number": "67766098",
        "postal_code": "128036"
    },
    {
        "address": "152 Beach Road 11-05",
        "charged_under_id": 1,
        "company_email": "angelina.bartoletti@walsh.com",
        "company_name": "Jerde and Sons",
        "description": "Diverse Modular Firmware",
        "gst": true,
        "gst_show": true,
        "name": "Stacy Reed",
        "p1_name": "Stacy Reed",
        "p1_phone_number": "62934960",
        "postal_code": "189721"
    },
    {
        "address": "Block 28 Tomlinson Road, 10-34 Kum Hing Court",
        "charged_under_id": 1,
        "company_email": "hsanford@gutmann.biz",
        "company_name": "Cole-Wehner",
        "description": "Function-Based Explicit Openarchitecture",
        "gst": true,
        "gst_show": true,
        "name": "Laurie Ramirez",
        "p1_name": "Laurie Ramirez",
        "p1_phone_number": "65-65-67350216",
        "postal_code": "247854"
    },
    {
        "address": "31 Kaki Bt Rd 3, Techlink #05-07,",
        "charged_under_id": 1,
        "company_email": "francisco.torp@leuschke.com",
        "company_name": "Rosenbaum, Stroman and Rath",
        "description": "Re-Engineered Object-Oriented Emulation",
        "gst": true,
        "gst_show": true,
        "name": "Jennifer Scott",
        "p1_name": "Jennifer Scott",
        "p1_phone_number": "62960934",
        "postal_code": "417818"
    },
    {
        "address": "2 Balestier Road 03-695 Balestier Hill Shopping Centre",
        "charged_under_id": 1,
        "company_email": "gutmann.dorothy@rolfson.com",
        "company_name": "Doyle Inc",
        "description": "Versatile Clear-Thinking Database",
        "gst": true,
        "gst_show": true,
        "name": "Derrick Kelly",
        "p1_name": "Derrick Kelly",
        "p1_phone_number": "62516019",
        "postal_code": "320002"
    },
    {
        "address": "Far East Square 133 Amoy Street #01-01",
        "charged_under_id": 1,
        "company_email": "brent.bednar@white.org",
        "company_name": "Rogahn, Kuhic and Breitenberg",
        "description": "Devolved Fresh-Thinking Concept",
        "gst": true,
        "gst_show": true,
        "name": "Joseph Walters",
        "p1_name": "Joseph Walters",
        "p1_phone_number": "65361331",
        "postal_code": "049962"
    },
    {
        "address": "2 Lorong Telok",
        "charged_under_id": 1,
        "company_email": "phoebe.mueller@west.com",
        "company_name": "Nikolaus, Stehr and Jaskolski",
        "description": "Stand-Alone Disintermediate Interface",
        "gst": true,
        "gst_show": true,
        "name": "William Carr",
        "p1_name": "William Carr",
        "p1_phone_number": "64350824",
        "postal_code": "049015"
    },
    {
        "address": "Suntec City Mall 3 Temasek Boulevard #01-199",
        "charged_under_id": 1,
        "company_email": "oreichert@morar.com",
        "company_name": "Collins, Nienow and Rowe",
        "description": "User-Centric Non-Volatile Migration",
        "gst": true,
        "gst_show": true,
        "name": "Latoya Mckenzie",
        "p1_name": "Latoya Mckenzie",
        "p1_phone_number": "63337575",
        "postal_code": "038983"
    },
    {
        "address": "402 Orchard Road #05-23 Delfi Orchard",
        "charged_under_id": 1,
        "company_email": "senger.isom@rosenbaum.net",
        "company_name": "Doyle Ltd",
        "description": "Extended Web-Enabled Superstructure",
        "gst": true,
        "gst_show": true,
        "name": "Donna Richard",
        "p1_name": "Donna Richard",
        "p1_phone_number": "68360674",
        "postal_code": "238876"
    },
    {
        "address": "1 Farrer Road 06-06 Tulip Garden",
        "charged_under_id": 1,
        "company_email": "fhilpert@rosenbaum.net",
        "company_name": "Kessler and Sons",
        "description": "Synergized Client-Driven Forecast",
        "gst": true,
        "gst_show": true,
        "name": "Becky Davis",
        "p1_name": "Becky Davis",
        "p1_phone_number": "64635140",
        "postal_code": "268817"
    },
    {
        "address": "80 Anson Road 28-04 Fuji Xerox Towers",
        "charged_under_id": 1,
        "company_email": "flo.von@reinger.net",
        "company_name": "Goodwin-Dach",
        "description": "Re-Contextualized Multimedia Productivity",
        "gst": true,
        "gst_show": true,
        "name": "Jesse Chase",
        "p1_name": "Jesse Chase",
        "p1_phone_number": "62221111",
        "postal_code": "079907"
    },
    {
        "address": "66 Tannery Lane",
        "charged_under_id": 1,
        "company_email": "bo.effertz@schimmel.org",
        "company_name": "Batz Ltd",
        "description": "Centralized Real-Time Core",
        "gst": true,
        "gst_show": true,
        "name": "Alex Nelson",
        "p1_name": "Alex Nelson",
        "p1_phone_number": "65 6844 3758",
        "postal_code": "347805"
    },
    {
        "address": "360 Orchard Road #05-02A International Building",
        "charged_under_id": 1,
        "company_email": "jaron.collins@mckenzie.net",
        "company_name": "Ritchie and Sons",
        "description": "Robust Asynchronous Alliance",
        "gst": true,
        "gst_show": true,
        "name": "Suzanne Brooks",
        "p1_name": "Suzanne Brooks",
        "p1_phone_number": "67348245",
        "postal_code": "238869"
    },
    {
        "address": "14 Scotts Road #02-24 Far East Plaza",
        "charged_under_id": 1,
        "company_email": "lbotsford@ledner.com",
        "company_name": "Deckow-Lang",
        "description": "Balanced Needs-Based Hierarchy",
        "gst": true,
        "gst_show": true,
        "name": "David Ramos",
        "p1_name": "David Ramos",
        "p1_phone_number": "67341150",
        "postal_code": "228213"
    },
    {
        "address": "Blk 19, Toa Payoh Ind Pk #01-1035",
        "charged_under_id": 1,
        "company_email": "orin23@trantow.com",
        "company_name": "Herman Ltd",
        "description": "Realigned Didactic Matrix",
        "gst": true,
        "gst_show": true,
        "name": "Diana Simmons",
        "p1_name": "Diana Simmons",
        "p1_phone_number": "65-62521479",
        "postal_code": "319071"
    },
    {
        "address": "BLK 2023 BUKIT BATOK STREET 23, #03-94",
        "charged_under_id": 1,
        "company_email": "gunnar.feest@waelchi.org",
        "company_name": "Legros-Gulgowski",
        "description": "Decentralized Analyzing Complexity",
        "gst": true,
        "gst_show": true,
        "name": "Anthony Stokes",
        "p1_name": "Anthony Stokes",
        "p1_phone_number": "65662347",
        "postal_code": "659528"
    },
    {
        "address": "351 CHAI CHEE STREET",
        "charged_under_id": 1,
        "company_email": "christian21@stokes.com",
        "company_name": "Luettgen-Flatley",
        "description": "Multi-Tiered Impactful Attitude",
        "gst": true,
        "gst_show": true,
        "name": "Henry Alexander",
        "p1_name": "Henry Alexander",
        "p1_phone_number": "62446612",
        "postal_code": "468982"
    },
    {
        "address": "6 Loyang Way 4",
        "charged_under_id": 1,
        "company_email": "ewintheiser@paucek.net",
        "company_name": "Kris, Wilderman and Sanford",
        "description": "Operative Fault-Tolerant Benchmark",
        "gst": true,
        "gst_show": true,
        "name": "Kelly Owen",
        "p1_name": "Kelly Owen",
        "p1_phone_number": "67479928",
        "postal_code": "507605"
    },
    {
        "address": "20 Mccallum Street 14-03 Asia Chambers",
        "charged_under_id": 1,
        "company_email": "yundt.doris@herzog.info",
        "company_name": "Ritchie LLC",
        "description": "Front-Line Fresh-Thinking Implementation",
        "gst": true,
        "gst_show": true,
        "name": "Terry Bailey Jr.",
        "p1_name": "Terry Bailey Jr.",
        "p1_phone_number": "63233131",
        "postal_code": "069046"
    },
    {
        "address": "50A Foch Road 03-00",
        "charged_under_id": 1,
        "company_email": "gerardo99@wolf.com",
        "company_name": "Jacobi, Murray and Sanford",
        "description": "Re-Engineered Analyzing Orchestration",
        "gst": true,
        "gst_show": true,
        "name": "Martin Moore",
        "p1_name": "Martin Moore",
        "p1_phone_number": "63920116",
        "postal_code": "209273"
    },
    {
        "address": "39 Tampines Street 92 Form Industrial Building",
        "charged_under_id": 1,
        "company_email": "bschultz@effertz.org",
        "company_name": "Nitzsche LLC",
        "description": "Adaptive Intermediate Matrix",
        "gst": true,
        "gst_show": true,
        "name": "Mr. Adam Foster",
        "p1_name": "Mr. Adam Foster",
        "p1_phone_number": "67407408",
        "postal_code": "528883"
    },
    {
        "address": "11 JALAN BATU 05-154",
        "charged_under_id": 1,
        "company_email": "amari.wuckert@becker.com",
        "company_name": "Fahey PLC",
        "description": "User-Centric Methodical Opensystem",
        "gst": true,
        "gst_show": true,
        "name": "Shawn Stuart",
        "p1_name": "Shawn Stuart",
        "p1_phone_number": "63457558",
        "postal_code": "431011"
    },
    {
        "address": "201 Woodlands Avenue 9 05-50",
        "charged_under_id": 1,
        "company_email": "gerdman@osinski.com",
        "company_name": "Kihn, Ledner and Becker",
        "description": "Fundamental Attitude-Oriented Concept",
        "gst": true,
        "gst_show": true,
        "name": "Lauren Rodriguez",
        "p1_name": "Lauren Rodriguez",
        "p1_phone_number": "67569723",
        "postal_code": "738955"
    },
    {
        "address": "18 tuas crescent",
        "charged_under_id": 1,
        "company_email": "larkin.mellie@schmitt.net",
        "company_name": "Kunze Ltd",
        "description": "Implemented 4Thgeneration Encoding",
        "gst": true,
        "gst_show": true,
        "name": "Madeline Murray",
        "p1_name": "Madeline Murray",
        "p1_phone_number": "0 6861 0936",
        "postal_code": "638712"
    },
    {
        "address": "BLK 38 DEFU LANE 10#01-19",
        "charged_under_id": 1,
        "company_email": "frowe@denesik.com",
        "company_name": "Kuhlman Group",
        "description": "Monitored Bandwidth-Monitored Groupware",
        "gst": true,
        "gst_show": true,
        "name": "April Jackson",
        "p1_name": "April Jackson",
        "p1_phone_number": "62884650",
        "postal_code": "539215"
    },
    {
        "address": "Seletar Hills Estate 11 Jalan Keruing",
        "charged_under_id": 1,
        "company_email": "mgerhold@schinner.com",
        "company_name": "Langosh, Stracke and Jones",
        "description": "Business-Focused Interactive Help-Desk",
        "gst": true,
        "gst_show": true,
        "name": "Henry Wright",
        "p1_name": "Henry Wright",
        "p1_phone_number": "64832074",
        "postal_code": "808932"
    },
    {
        "address": "5 Temasek Boulevard 06-04 Suntec City Tower 5",
        "charged_under_id": 1,
        "company_email": "mrippin@koelpin.com",
        "company_name": "Stracke, Wiegand and Jaskolski",
        "description": "Universal Background Openarchitecture",
        "gst": true,
        "gst_show": true,
        "name": "Rachel Foster",
        "p1_name": "Rachel Foster",
        "p1_phone_number": "63388680",
        "postal_code": "038985"
    },
    {
        "address": "808 French Road ,07-163 Kitchener Complex",
        "charged_under_id": 1,
        "company_email": "xhodkiewicz@oreilly.com",
        "company_name": "Gleason-Leffler",
        "description": "Customer-Focused Neutral Migration",
        "gst": true,
        "gst_show": true,
        "name": "Gregory Frank",
        "p1_name": "Gregory Frank",
        "p1_phone_number": "65-90282835",
        "postal_code": "200808"
    },
    {
        "address": "3 Pickering Street #02-50 China Square Central - Nankin Row",
        "charged_under_id": 1,
        "company_email": "rey.west@pfannerstill.com",
        "company_name": "Fisher, Nicolas and Douglas",
        "description": "Re-Engineered Client-Driven Openarchitecture",
        "gst": true,
        "gst_show": true,
        "name": "Diane Taylor",
        "p1_name": "Diane Taylor",
        "p1_phone_number": "65570260",
        "postal_code": "048660"
    },
    {
        "address": "30 Kaki Bukit Industrial Terrace",
        "charged_under_id": 1,
        "company_email": "nitzsche.jensen@rosenbaum.com",
        "company_name": "Kemmer, Bruen and Gaylord",
        "description": "Up-Sized Actuating Success",
        "gst": true,
        "gst_show": true,
        "name": "Angela Allison",
        "p1_name": "Angela Allison",
        "p1_phone_number": "65-6741 4529",
        "postal_code": "416110"
    },
    {
        "address": "171 Kampong Ampat 06-09",
        "charged_under_id": 1,
        "company_email": "gabe80@hauck.org",
        "company_name": "Cassin, Koss and Botsford",
        "description": "Multi-Lateral Dedicated Hierarchy",
        "gst": true,
        "gst_show": true,
        "name": "Nicholas Vargas PhD",
        "p1_name": "Nicholas Vargas PhD",
        "p1_phone_number": "67415925",
        "postal_code": "368330"
    },
    {
        "address": "51 Telok Ayer St #01-11",
        "charged_under_id": 1,
        "company_email": "madeline.bosco@gaylord.com",
        "company_name": "Hilpert, Champlin and Anderson",
        "description": "Profound Demand-Driven Challenge",
        "gst": true,
        "gst_show": true,
        "name": "Melissa Howard",
        "p1_name": "Melissa Howard",
        "p1_phone_number": "64382659",
        "postal_code": "048441"
    },
    {
        "address": "392B SIMS AVE",
        "charged_under_id": 1,
        "company_email": "kirsten09@block.net",
        "company_name": "Purdy, Jerde and Gutkowski",
        "description": "Automated Impactful Synergy",
        "gst": true,
        "gst_show": true,
        "name": "Patrick Fields",
        "p1_name": "Patrick Fields",
        "p1_phone_number": "67435767",
        "postal_code": "387537"
    },
    {
        "address": "24 WHOLESALE CENTRE 01-180",
        "charged_under_id": 1,
        "company_email": "bella.gutmann@dare.com",
        "company_name": "Tromp, Treutel and Lynch",
        "description": "Re-Engineered Content-Based Solution",
        "gst": true,
        "gst_show": true,
        "name": "Stephen Morales",
        "p1_name": "Stephen Morales",
        "p1_phone_number": "67748265",
        "postal_code": "110024"
    },
    {
        "address": "10 Ubi Crescent #05-05 Ubi Tech Park",
        "charged_under_id": 1,
        "company_email": "bogisich.vance@boyle.net",
        "company_name": "Robel, Rodriguez and Kessler",
        "description": "Persevering Disintermediate Project",
        "gst": true,
        "gst_show": true,
        "name": "Joyce Huerta",
        "p1_name": "Joyce Huerta",
        "p1_phone_number": "65-9673 9621",
        "postal_code": "408564"
    },
    {
        "address": "80 Anson Road #28-03 FUJI XEROX TOWERS",
        "charged_under_id": 1,
        "company_email": "corbin.sipes@macejkovic.com",
        "company_name": "Gleason, Koelpin and Schamberger",
        "description": "Customizable Multimedia Budgetarymanagement",
        "gst": true,
        "gst_show": true,
        "name": "Richard Cohen",
        "p1_name": "Richard Cohen",
        "p1_phone_number": "62250579",
        "postal_code": "079907"
    },
    {
        "address": "715 YISHUN STREET 71 08-286",
        "charged_under_id": 1,
        "company_email": "cberge@reichel.com",
        "company_name": "Padberg PLC",
        "description": "Advanced Cohesive Circuit",
        "gst": true,
        "gst_show": true,
        "name": "Jeff Mcmahon",
        "p1_name": "Jeff Mcmahon",
        "p1_phone_number": "62957129",
        "postal_code": "760715"
    },
    {
        "address": "190 Shopping Centre 04-20 Clemenceau Avenue",
        "charged_under_id": 1,
        "company_email": "mckenzie.bryce@marks.net",
        "company_name": "Stroman-Bosco",
        "description": "Polarised Zerodefect Complexity",
        "gst": true,
        "gst_show": true,
        "name": "Bobby Rodriguez",
        "p1_name": "Bobby Rodriguez",
        "p1_phone_number": "63345889",
        "postal_code": "239924"
    },
    {
        "address": "16 Mohamed Sultan Road #02-32",
        "charged_under_id": 1,
        "company_email": "kristoffer.bailey@vonrueden.com",
        "company_name": "Turner Inc",
        "description": "Triple-Buffered Full-Range Functionalities",
        "gst": true,
        "gst_show": true,
        "name": "Keith Curry",
        "p1_name": "Keith Curry",
        "p1_phone_number": "62876163",
        "postal_code": "238965"
    },
    {
        "address": "73 Science Park Drive #02-05 Cintech I",
        "charged_under_id": 1,
        "company_email": "breitenberg.haley@ritchie.com",
        "company_name": "Conroy Inc",
        "description": "Team-Oriented Web-Enabled Openarchitecture",
        "gst": true,
        "gst_show": true,
        "name": "Holly Phelps",
        "p1_name": "Holly Phelps",
        "p1_phone_number": "67781637",
        "postal_code": "118254"
    },
    {
        "address": "41 Holland Dr #01-23",
        "charged_under_id": 1,
        "company_email": "ayana.considine@terry.biz",
        "company_name": "Waelchi-D'Amore",
        "description": "Profit-Focused 4Thgeneration Hierarchy",
        "gst": true,
        "gst_show": true,
        "name": "Thomas Johnson",
        "p1_name": "Thomas Johnson",
        "p1_phone_number": "67784761",
        "postal_code": "270041"
    },
    {
        "address": "01-01 and 01-57 Orchard Plaza 150 Orchard Road",
        "charged_under_id": 1,
        "company_email": "icremin@ortiz.org",
        "company_name": "McCullough Inc",
        "description": "Managed Intermediate Moderator",
        "gst": true,
        "gst_show": true,
        "name": "Jessica Wright",
        "p1_name": "Jessica Wright",
        "p1_phone_number": "97472135",
        "postal_code": "238841"
    },
    {
        "address": "7500A Beach Road The Plaza",
        "charged_under_id": 1,
        "company_email": "weber.johathan@spencer.com",
        "company_name": "Bradtke, Donnelly and Stroman",
        "description": "Implemented 5Thgeneration Openarchitecture",
        "gst": true,
        "gst_show": true,
        "name": "Melissa Howe",
        "p1_name": "Melissa Howe",
        "p1_phone_number": "62962588",
        "postal_code": "199591"
    },
    {
        "address": "10 Anson Road #12-14 International Plaza",
        "charged_under_id": 1,
        "company_email": "amie.ziemann@erdman.com",
        "company_name": "Quigley-Schinner",
        "description": "Diverse Composite Synergy",
        "gst": true,
        "gst_show": true,
        "name": "Jason Smith",
        "p1_name": "Jason Smith",
        "p1_phone_number": "62238137",
        "postal_code": "079903"
    },
    {
        "address": "55 Jalan Lim Tai See 03-08 Promise Garden",
        "charged_under_id": 1,
        "company_email": "weber.garrison@goyette.net",
        "company_name": "Rau-Effertz",
        "description": "Synchronised Scalable Functionalities",
        "gst": true,
        "gst_show": true,
        "name": "Richard Holmes",
        "p1_name": "Richard Holmes",
        "p1_phone_number": "62270013",
        "postal_code": "268386"
    },
    {
        "address": "Lam Soon Industrial Building 63 Hillview Avenue #09-23",
        "charged_under_id": 1,
        "company_email": "neva.fisher@mann.com",
        "company_name": "West-Beatty",
        "description": "User-Friendly Well-Modulated Challenge",
        "gst": true,
        "gst_show": true,
        "name": "Natasha Myers",
        "p1_name": "Natasha Myers",
        "p1_phone_number": "68925760",
        "postal_code": "669569"
    },
    {
        "address": "11 COLLYER QUAY, #12-04",
        "charged_under_id": 1,
        "company_email": "iwalter@harvey.biz",
        "company_name": "Crooks-Tromp",
        "description": "Re-Engineered Intangible Graphicaluserinterface",
        "gst": true,
        "gst_show": true,
        "name": "Desiree Austin",
        "p1_name": "Desiree Austin",
        "p1_phone_number": "64382293",
        "postal_code": "049317"
    },
    {
        "address": "Springleaf Garden 6 Springleaf View",
        "charged_under_id": 1,
        "company_email": "genevieve51@bogisich.com",
        "company_name": "Bergnaum-Conn",
        "description": "De-Engineered Optimal Infrastructure",
        "gst": true,
        "gst_show": true,
        "name": "David Dominguez",
        "p1_name": "David Dominguez",
        "p1_phone_number": "64540176",
        "postal_code": "787912"
    },
    {
        "address": "190 190 Ang Mo Kio Avenue 8 01-02",
        "charged_under_id": 1,
        "company_email": "isaac.jacobs@stroman.org",
        "company_name": "Cruickshank, Mante and Jast",
        "description": "Vision-Oriented 3Rdgeneration Parallelism",
        "gst": true,
        "gst_show": true,
        "name": "Samantha Henry",
        "p1_name": "Samantha Henry",
        "p1_phone_number": "64513143",
        "postal_code": "568046"
    },
    {
        "address": "20 Changi Road",
        "charged_under_id": 1,
        "company_email": "mollie.leuschke@klein.com",
        "company_name": "Gutmann, Towne and Kiehn",
        "description": "Profound Object-Oriented Leverage",
        "gst": true,
        "gst_show": true,
        "name": "Paul Walter",
        "p1_name": "Paul Walter",
        "p1_phone_number": "65-6-4569947",
        "postal_code": "659480"
    },
    {
        "address": "11 Collyer Quay #01-24 The Arcade",
        "charged_under_id": 1,
        "company_email": "cynthia.gislason@kshlerin.com",
        "company_name": "Little and Sons",
        "description": "Switchable 24/7 Application",
        "gst": true,
        "gst_show": true,
        "name": "Christy Mcguire",
        "p1_name": "Christy Mcguire",
        "p1_phone_number": "62226996",
        "postal_code": "049317"
    },
    {
        "address": "21 Science Park Road 03-19 The Aquarius, S'pore Science Pk II,",
        "charged_under_id": 1,
        "company_email": "marguerite69@metz.com",
        "company_name": "Altenwerth-Mertz",
        "description": "Profit-Focused 24Hour Graphicaluserinterface",
        "gst": true,
        "gst_show": true,
        "name": "Karen Montoya",
        "p1_name": "Karen Montoya",
        "p1_phone_number": "68734640",
        "postal_code": "117628"
    },
    {
        "address": "23 Hume Ave, 04-06",
        "charged_under_id": 1,
        "company_email": "vgoldner@lebsack.com",
        "company_name": "Greenholt Inc",
        "description": "Fully-Configurable Motivating Workforce",
        "gst": true,
        "gst_show": true,
        "name": "Mary Stevens",
        "p1_name": "Mary Stevens",
        "p1_phone_number": "65-68927617",
        "postal_code": "598729"
    },
    {
        "address": "5000 ANG MO KIO AVE 5 TECHPLACE 2 04-08",
        "charged_under_id": 1,
        "company_email": "ihowe@erdman.biz",
        "company_name": "Goldner-Greenholt",
        "description": "Networked Nextgeneration Challenge",
        "gst": true,
        "gst_show": true,
        "name": "Michael Pittman",
        "p1_name": "Michael Pittman",
        "p1_phone_number": "64831322",
        "postal_code": "569870"
    },
    {
        "address": "Defu Industrial Park A 30 Defu Lane 3",
        "charged_under_id": 1,
        "company_email": "ksanford@gusikowski.com",
        "company_name": "Rau PLC",
        "description": "Cross-Group Bandwidth-Monitored Implementation",
        "gst": true,
        "gst_show": true,
        "name": "Denise Love",
        "p1_name": "Denise Love",
        "p1_phone_number": "64876326",
        "postal_code": "539449"
    },
    {
        "address": "115A C'Wealth Dr #05-24 Tanglin Halt Ind Est S()",
        "charged_under_id": 1,
        "company_email": "hlegros@prohaska.com",
        "company_name": "Cassin-Reynolds",
        "description": "Self-Enabling Human-Resource Implementation",
        "gst": true,
        "gst_show": true,
        "name": "Melissa Jarvis",
        "p1_name": "Melissa Jarvis",
        "p1_phone_number": "(65) 64710710",
        "postal_code": "149596"
    },
    {
        "address": "3000 Marsiling Road",
        "charged_under_id": 1,
        "company_email": "njacobs@hermiston.com",
        "company_name": "Mraz, Kub and Padberg",
        "description": "Expanded Optimizing Neural-Net",
        "gst": true,
        "gst_show": true,
        "name": "Kristy Dominguez",
        "p1_name": "Kristy Dominguez",
        "p1_phone_number": "62690816",
        "postal_code": "739108"
    },
    {
        "address": "10 Anson Road #20-12 International Plaza",
        "charged_under_id": 1,
        "company_email": "sibyl.bogisich@hill.net",
        "company_name": "Walter-Robel",
        "description": "User-Centric National Adapter",
        "gst": true,
        "gst_show": true,
        "name": "John Collier",
        "p1_name": "John Collier",
        "p1_phone_number": "67771928",
        "postal_code": "079903"
    },
    {
        "address": "Royal Sporting House - Tanglin Mall, 163 Tanglin Road,",
        "charged_under_id": 1,
        "company_email": "aron09@witting.com",
        "company_name": "Sauer, Murray and Bartoletti",
        "description": "User-Friendly Fault-Tolerant Model",
        "gst": true,
        "gst_show": true,
        "name": "Russell Kirk",
        "p1_name": "Russell Kirk",
        "p1_phone_number": "65 6735 3485",
        "postal_code": "247933"
    },
    {
        "address": "3 New Bugis St #01-08",
        "charged_under_id": 1,
        "company_email": "gschultz@considine.com",
        "company_name": "Ryan LLC",
        "description": "Reverse-Engineered Discrete Hub",
        "gst": true,
        "gst_show": true,
        "name": "Margaret Miller",
        "p1_name": "Margaret Miller",
        "p1_phone_number": "63348727",
        "postal_code": "188867"
    },
    {
        "address": "163 TRAS STREET, #07-02",
        "charged_under_id": 1,
        "company_email": "lorn@dach.biz",
        "company_name": "Bahringer-Runolfsdottir",
        "description": "Enterprise-Wide Client-Server Paradigm",
        "gst": true,
        "gst_show": true,
        "name": "Matthew Miranda",
        "p1_name": "Matthew Miranda",
        "p1_phone_number": "63230730",
        "postal_code": "079024"
    },
    {
        "address": "Block 202 Bedok North Street 1, #01-479/481",
        "charged_under_id": 1,
        "company_email": "lizeth49@douglas.org",
        "company_name": "Roberts-Trantow",
        "description": "Distributed Directional Interface",
        "gst": true,
        "gst_show": true,
        "name": "Ashley Thomas",
        "p1_name": "Ashley Thomas",
        "p1_phone_number": "65 6445 9562",
        "postal_code": "460202"
    },
    {
        "address": "422 EAST COAST ROAD EAST GROVE",
        "charged_under_id": 1,
        "company_email": "pearl.dicki@franecki.biz",
        "company_name": "Kling LLC",
        "description": "User-Centric Exuding Focusgroup",
        "gst": true,
        "gst_show": true,
        "name": "Katherine Maxwell",
        "p1_name": "Katherine Maxwell",
        "p1_phone_number": "63449840",
        "postal_code": "429009"
    }
]